ToTheChase/Models/Exchange.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToTheChase.Models
{
    public class Exchange
    {
        public int ExchangeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool IsMajorExchange { get; set; }

    }
}

ToTheChase/Models/Leg.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToTheChase.Models
{
    public class Leg
    {
        public int LegID { get; set; }
        [Display(Name ="Leg Number")]
        public int LegNumber { get; set; }
        [Display(Name ="Lenght (mi)")]
        public double LengthInMiles { get; set; }
        public Exchange StartExchange { get; set; }
        public Exchange EndExchange { get; set; }
        [Display(Name ="Leg Difficulty")]
        public LegDifficulty LegDifficulty { get; set; }

        [Display(Name ="Runner")]
        public int AssignedRunnerId { get; set; }
        
        public Runner Runner { get
            {
                if(AssignedRunnerId > 0)
                {
                    var db = new Data.ToTheChaseContext();
                    return db.GetRunnerById(AssignedRunnerId);
                }
                return new Runner() { FirstName = "Unassigned"};
            } }
    }
}

ToTheChase/Models/LegDifficulty.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToTheChase.Models
{
    public enum LegDifficulty
    {
        Easy,Medium,Difficult
    }
}

ToTheChase/Models/Runner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToTheChase.Models
{
    public class Runner
    {
        [Required]
        public int RunnerID { get; set; }
        [Display(Name ="Runner Number")]
        public int RunnerNumber { get; set; }
        [Display(Name ="First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name ="Pace in Minutes")]
        public int PaceMinutes { get; set; }
        [Display(Name = "Pace in Seconds")]
        public int PaceSeconds { get; set; }
        [Display(Name = "Van Type")]
        public Van Van;
        public List<int> Legs { get; set; }
    }
}

ToTheChase/Models/Van.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ToTheChase.Models
{
    public enum Van
    {
        Van1,
        Van2
    }
}

ToTheChase/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheChase.Data;

namespace ToTheChase.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


    }
}

ToTheChase/Controllers/LegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheChase.Data;
using ToTheChase.Models;

namespace ToTheChase.Controllers
{
    public class LegController : Controller
    {
        private readonly IToTheChaseData db;

        public LegController(IToTheChaseData db)
        {
            this.db = db;
        }

        // GET: Legs
        public ActionResult Legs()
        {
            var model = db.Legs();
            return View(model);
        }

        [HttpGet]
        public ActionResult Create()
        {
            var model = new Leg();
            ViewBag.Runners = db.GetAllRunners();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Leg leg)
        {
            if (ModelState.IsValid)
            {
                db.AddLeg(leg);
                return RedirectToAction("Legs");
            }
            return View(leg);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var leg = db.GetLegById(id);
            ViewBag.Runners = db.GetAllRunners();
            return View(leg);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Leg leg)
        {
            if (ModelState.IsValid)
            {
                db.UpdateLeg(leg);
                return RedirectToAction("Legs");
            }
            return View(leg);
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var model = db.GetLegById(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.GetLegById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string s)
        {
            db.RemoveLeg(id);
            return RedirectToAction("Legs");
        }

    }
}

ToTheChase/Controllers/RunnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToTheChase.Data;
using ToTheChase.Models;

namespace ToTheChase.Controllers
{
    public class RunnerController : Controller
    {
        private readonly IToTheChaseData db;

        /// <summary>
        /// Using dependency inject here to inject the appropriate data class.
        /// </summary>
        /// <param name="db"></param>
        public RunnerController(IToTheChaseData db)
        {
            this.db = db;
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Runner runner)
        {
            if (ModelState.IsValid)
            {
                db.AddRunner(runner);
                return RedirectToAction("Runners");
            }
            return View(runner);
        }

        public ActionResult Details(int id)
        {
            var model = db.GetRunnerById(id);
            return View(model);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var model = db.GetRunnerById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Runner runner)
        {
            if (ModelState.IsValid)
            {
                db.UpdateRunner(runner);
                return RedirectToAction("Runners");
            }
            return View();
        }

        public ActionResult Runners()
        {
            var model = db.GetAllRunners();
            return View(model);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var model = db.GetRunnerById(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, string s)
        {
            if (ModelState.IsValid)
            {
                db.RemoveRunner(id);
                return RedirectToAction("Runners");
            }
            return View();
        }
    }
}

ToTheChase/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ToTheChase/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ToTheChase/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ToTheChase/Views/Leg/Create.cshtml
@model ToTheChase.Models.Leg

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leg</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.LegNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LegNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LegNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LegDifficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LegDifficulty, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LegDifficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedRunnerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssignedRunnerId, new SelectList(ViewBag.Runners,"RunnerID","FirstName") ,htmlAttributes : new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.AssignedRunnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LengthInMiles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LengthInMiles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LengthInMiles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Legs")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheChase/Views/Leg/Delete.cshtml
@model ToTheChase.Models.Leg

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Leg</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LegNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedRunnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedRunnerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LegDifficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegDifficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LengthInMiles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LengthInMiles)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.Hidden("id", new { id = Model.LegID})
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Legs")
        </div>
    }
</div>

ToTheChase/Views/Leg/Details.cshtml
@model ToTheChase.Models.Leg

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Leg</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LegNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.AssignedRunnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AssignedRunnerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LegDifficulty)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LegDifficulty)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LengthInMiles)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LengthInMiles)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.LegID }) |
    @Html.ActionLink("Back to List", "Legs")
</p>

ToTheChase/Views/Leg/Edit.cshtml
@model ToTheChase.Models.Leg

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Leg</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LegID)

        <div class="form-group">
            @Html.LabelFor(model => model.LegNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LegNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LegNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AssignedRunnerId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AssignedRunnerId, new SelectList(ViewBag.Runners,"RunnerID","FirstName"),htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AssignedRunnerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LegDifficulty, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.LegDifficulty, htmlAttributes: new { @class = "form-control dropdown-toggle"} )
                @Html.ValidationMessageFor(model => model.LegDifficulty, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LengthInMiles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LengthInMiles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LengthInMiles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Legs")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheChase/Views/Leg/Legs.cshtml
@model IEnumerable<ToTheChase.Models.Leg>

@{
    ViewBag.Title = "Legs";
}

<h2>Legs</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.LegNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AssignedRunnerId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LegDifficulty)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LengthInMiles)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LegNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Runner.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LegDifficulty)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LengthInMiles)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LegID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LegID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LegID })
        </td>
    </tr>
}

</table>

ToTheChase/Views/Runner/Create.cshtml
@model ToTheChase.Models.Runner

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Runner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RunnerNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunnerNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunnerNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaceMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaceMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaceMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaceSeconds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaceSeconds, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaceSeconds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Runners")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToTheChase/Views/Runner/Delete.cshtml
@model ToTheChase.Models.Runner

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Runner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RunnerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunnerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaceMinutes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaceMinutes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PaceSeconds)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PaceSeconds)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.Hidden("id", new { id = Model.RunnerID})
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Runners")
        </div>
    }
</div>

ToTheChase/Views/Runner/Details.cshtml
@model ToTheChase.Models.Runner

@{
    ViewBag.Title = "RunnerDetail";
}

<h2>Runner Detail</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RunnerNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RunnerNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            Pace
        </dt>

        <dd>
            @Html.Partial("PacePartial",Model)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RunnerID }) |
    @Html.ActionLink("Back to List", "Runners")
</p>

ToTheChase/Views/Runner/Edit.cshtml
@model ToTheChase.Models.Runner

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Runner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.RunnerID)

        <div class="form-group">
            @Html.LabelFor(model => model.RunnerNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RunnerNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RunnerNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaceMinutes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaceMinutes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaceMinutes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PaceSeconds, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PaceSeconds, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PaceSeconds, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Runners")
</div>

ToTheChase/Views/Runner/PacePartial.cshtml
@model ToTheChase.Models.Runner

<div>
   @Model.PaceMinutes : @(Model.PaceSeconds.ToString("D2"))
</div>

ToTheChase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Runners", "Runners", "Runner")</li>
                    <li>@Html.ActionLink("Legs", "Legs", "Leg")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>